# -*- coding: utf-8 -*-
"""jeroglificos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d98r602Kblwvmu3koNW0_kQBlJp5h99a
"""

# archivo: app_jeroglificos.py

import streamlit as st
import pandas as pd


# URL raw de tu Excel en GitHub
url = "https://github.com/JANETHSUSAN121/INTROGIT/raw/main/profesiones_jeroglificos.xlsx"

# Leer el Excel directamente desde GitHub
@st.cache_data
def load_data():
    df = pd.read_excel(url)
    return df

df = load_data()

# Configuración de la página
st.set_page_config(page_title="Diccionario de Profesiones", layout="wide")

st.title("Diccionario de Profesiones en Jeroglíficos 🏺")
st.markdown("Selecciona una profesión para ver su jeroglífico, transliteración y descripción.")

# Inicializar selección
if "seleccion" not in st.session_state:
    st.session_state["seleccion"] = None

# Crear dos columnas: galería y panel de detalles
galeria_col, detalles_col = st.columns([3, 2])

# Galería de tarjetas (2 tarjetas por fila)
num_cols = 2
tarjetas = galeria_col.columns(num_cols)

for idx, row in df.iterrows():
    col = tarjetas[idx % num_cols]
    with col:
        # Mostrar imagen si existe en tu Excel
        if "Imagen" in df.columns and pd.notna(row["Imagen"]):
            st.image(row["Imagen"], width=150)
        # Botón para seleccionar profesión
        if st.button(row["profesion"], key=idx):
            st.session_state["seleccion"] = idx

# Mostrar detalles de la profesión seleccionada
if st.session_state["seleccion"] is not None:
    row = df.loc[st.session_state["seleccion"]]
    detalles_col.subheader(f"{row['profesion']}")
    detalles_col.markdown(f"**Jeroglífico:** {row['jeroglifico']}")
    detalles_col.markdown(f"**Transliteración:** {row['transliteracion']}")
    detalles_col.markdown(f"**Descripción:** {row['descripcion']}")
    # Mostrar imagen grande si existe
    if "Imagen" in df.columns and pd.notna(row["Imagen"]):
        detalles_col.image(row["Imagen"], use_column_width=True)


# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %pip install openpyxl
